In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
# import warnings
# warnings.simplefilter('ignore')

In [2]:
dict = {'Time (hr)': [2.7 , 1.4, 3.3, 1.3, 3,7.6,  5.9, 6.9, 8.6,7.7 ],
        'Sentences(1=1000)': [2.5, 2.3, 2.4, 1.8, 3, 2.7, 2.2, 1.8, 3.5, 3.5], 
       'Article Type': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]}
df = pd.DataFrame(dict)
df

Time (hr)  Sentences(1=1000)  Article Type
0        2.7                2.5             0
1        1.4                2.3             0
2        3.3                2.4             0
3        1.3                1.8             0
4        3.0                3.0             0
5        7.6                2.7             1
6        5.9                2.2             1
7        6.9                1.8             1
8        8.6                3.5             1
9        7.7                3.5             1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Time (hr)          10 non-null     float64
 1   Sentences(1=1000)  10 non-null     float64
 2   Article Type       10 non-null     int64  
dtypes: float64(2), int64(1)
memory usage: 372.0 bytes


In [4]:
df.describe()

Time (hr)  Sentences(1=1000)  Article Type
count  10.000000          10.000000     10.000000
mean    4.840000           2.570000      0.500000
std     2.788946           0.611101      0.527046
min     1.300000           1.800000      0.000000
25%     2.775000           2.225000      0.000000
50%     4.600000           2.450000      0.500000
75%     7.425000           2.925000      1.000000
max     8.600000           3.500000      1.000000

In [5]:
df.nunique()

Time (hr)            10
Sentences(1=1000)     8
Article Type          2
dtype: int64

In [6]:
df.isnull().sum()

Time (hr)            0
Sentences(1=1000)    0
Article Type         0
dtype: int64

In [7]:
X = df.iloc[:, :2]
X.columns

Index(['Time (hr)', 'Sentences(1=1000)'], dtype='object')

In [8]:
# y = np.array(df.iloc[: , 2:]).ravel()
y = df['Article Type']
y

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    1
8    1
9    1
Name: Article Type, dtype: int64

In [9]:
df.corr()

Time (hr)  Sentences(1=1000)  Article Type
Time (hr)           1.000000           0.509292      0.944884
Sentences(1=1000)   0.509292           1.000000      0.293234
Article Type        0.944884           0.293234      1.000000

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [12]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)


LogisticRegression()

In [13]:
y_hat = logreg.predict(X_test)
y_hat

array([1, 0, 1], dtype=int64)

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
print('confusion matrix: ', confusion_matrix(y_hat, y_test))
print('accuracy_score: ', accuracy_score(y_hat, y_test))

confusion matrix:  [[1 0]
 [0 2]]
accuracy_score:  1.0


In [15]:
logreg.predict(X.iloc[8:9])

array([1], dtype=int64)

In [16]:
svm = SVC()
svm.fit(X_train, y_train)

SVC()

In [17]:
new_hat = svm.predict(X_test)
new_hat

array([1, 0, 1], dtype=int64)

In [18]:
print('confusion matrix: ', confusion_matrix(new_hat, y_test))

confusion matrix:  [[1 0]
 [0 2]]


In [19]:
print('accuracy score :', accuracy_score(new_hat, y_test))

accuracy score : 1.0


In [23]:
rnd = RandomForestClassifier()
rnd.fit(X_train, y_train)

RandomForestClassifier()

In [24]:
rnd_ = rnd.predict(X_test)
rnd_

array([0, 0, 0], dtype=int64)

In [25]:
print('f1 score: ',f1_score(rnd_, y_test))

f1 score:  0.0
